config/routes.rb
ReedrR::Application.routes.draw do

  root 'feeds#index'

  resources :feeds
  get 'feeds/:id/load' => 'feeds#load'
  get 'feeds/:id/issues' => 'feeds#issues'
  get 'feeds/:id/transfer' => 'feeds#transfer'

  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def new
  end

  def create
    @feed = Feed.new(post_params)
    @feed.save
    
    redirect_to @feed
  end

  def show
    @feed = Feed.find(params[:id])
  end

  def load
    @issues = []
    feed_reader = FeedReader.new
    issues = feed_reader.read(Feed.find(params[:id]))
    issues.each do |issue_data|
      @issues << Issue.create(issue_data) unless Issue.where(guid: issue_data[:guid]).exists?
    end
  end

  def transfer
    issues = Issue.where(:synced => false)
    @transfered = 0
    issues.each do |issue|
      if post_to_readability(issue)
        issue.synced = true
        issue.save
        @transfered += 1
      end
    end
  end

  def issues
    @issues = Issue.all
  end

private
  def post_params
    params.require(:feed).permit(:title, :url)
  end

  def post_to_readability(issue)
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<h1>Feeds</h1>
<table>
<tr>
  <th>Title</th>
  <th>Url</th>
</tr>
<% @feeds.each do |feed| %>
<tr>
  <td><%= feed.title %></td>
  <td><%= feed.url %></td>
</tr>
<% end %>
</table>

app/views/feeds/issues.html.erb
<p>
  <strong><%= @issues.count %> issues available</strong>
</p>
<% @issues.each do |issue| %>
<p>
  <%= issue.guid %>
</p>
<p>
  <%= issue.title %>
</p>
<% end %>

app/views/feeds/load.html.erb
<p>
  <strong>
    <% if @issues.count > 0 %>
    <%= @issues.count %> new issues loaded to the database
    <% else %>
    everything up to date
    <% end %>
  </strong>
</p>
<% @issues.each do |issue| %>
<p>
  <%= issue.guid %>
</p>
<p>
  <%= issue.title %>
</p>
<% end %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>
<%= form_for :feed, url: feeds_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/feeds/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>
 
<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

app/views/feeds/transfer.html.erb
<p>
  <strong><%= @transfered %> issues transfered to readability</strong>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReedrR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>